### ISSUE TITLE
Add support for parent object fields in queries

### ISSUE THREAD

**Issue by jongpie** [jongpie/NebulaFramework#13]

**Comment by jamessimone** [comment]
I'd love to hear your thoughts on this, we had a use case for this and ended up having to hard code the SOQL :(

**Comment by jongpie** [comment]
Boooo to that. How'd you end up hardcoding it? I've got a few ideas on how to implement, but haven't spent much time working on it yet.

**Comment by jamessimone** [comment]
IE with SOQL itself: select Id
        from CallListItem__c
        where Lead__r.Status = :leadStatus

Sadface.  ALSO - we ended up hardcoding an aggregate result list and I think that more generic support for aggregrates would also be easy to add (except that in this specific use case, the parent object field was part of the aggregate where clause as well).  

I looked a bit into the describe calls with Bruce on this one, but it wasn't immediately obvious how to quickly extend the query builder to do what we wanted, so we went with the base implementation for now.  Really hoping to hear your thoughts on a more programmatic approach!

**Comment by jongpie** [comment]
I definitely need to research it more, but I'm thinking something like this might be doable.

Current method for adding a WHERE condition - this is to filter on the 'current' object (CallListItem__c in your example)
`public IQueryBuilder whereField(Schema.SObjectField field, QueryOperator operator, Object value) `

Possible new overloaded version for filtering on parent fields
`public IQueryBuilder whereField(Schema.SObjectField parentLookupField, Schema.SObjectField parentFieldToFilter, QueryOperator operator, Object value) `

And you'd implement your example like this....
`whereField(Schema.CallListItem__c.Lead__c, Schema.Lead.Status, new QueryOperator().EQUALS, 'Some Status') `

I haven't tested this, so I'm not 100% sure how feasible it is, but from an implementation standpoint... thoughts?

**Comment by jongpie** [comment]
Oh and I'd definitely love to have support for generic aggregate results within the framework - I think I even started on it at one point, but I wanted to get QueryBuilder stabilized for 'regular' SObjects before trying to make it work for aggregate results. But I think we should start looking at adding it now/soon.

**Comment by jamessimone** [comment]
public IQueryBuilder whereParentField(SObjectField parentLookupField, SObjectField parentFieldToFilter, QueryOperator operator, Object value) {

        String relationshipName = parentLookupField.getDescribe().getRelationshipName();
        String filterField = parentFieldToFilter.getDescribe().getName();
        String combinedLookupField = relationshipName + '.' + filterField;
        this.addToWhereClauseList(combinedLookupField, operator, value);

        return this;

    }


sorry for the janky styling, but this is working for the parent lookups

**Comment by jamessimone** [comment]
@jongpie actually I am pushing the implementation of this from QueryBuilder to QueryPredicate and subclassing it.  There is some procedural logic I've baked into QueryBuilder to append the correct string to the where clause list, but because the version of SObjectRepository we're running with has a generic "get" method run by QueryPredicates, pushing the logic down to that class allows for us to be much more flexible in extending each repository.  We can simply wrap the calls to parent object fields in the QueryPredicate (or subclass thereof) and still make use of the standard "get" without having to have more specific "getByxxxxxx" methods on each of the repos.  

I am putting some finishing touches on this and will push up the changes in a bit.

**Comment by jamessimone** [comment]
Aaaand backing out the QueryParentPredicate changes -   The work on aggregate results (#37) yielded a cleaner design through QueryBuilder.  Pushing up that work as well.
