### ISSUE TITLE
Add support for child object subselects in queries

### ISSUE THREAD

**Issue by jongpie** [jongpie/NebulaFramework#14]

**Comment by jongpie** [comment]
@jamessimone I think I´ve got a way to handle this feature, but just curious - do you guys have a big need for this feature in your implementation?

**Comment by jamessimone** [comment]
@jongpie  so far we haven't had the need.  One big use case I can think of would be once (if?) we move more onto the service side, since sub-selects for Case in particular has proven useful in the past.  That being said, at the moment, there is no practical difference between sub-selects and two queries.

**Comment by jongpie** [comment]
@jamessimone same for me, I haven't had a need to use them yet (especially considering I hate the syntax), but I think I've found a good way to handle including them in the parent object's repo queries.

One difference I found is that the sub-selects don't appear to count towards the limit of 100 queries per transaction - so querying for case, case comments and case tasks seem to count as 1 query (I was always under the impression that they counted as separate queries - 1 for the parent object, 1 for the child object). This guy claims that they count towards a different, hidden limit of 300 sub-selects https://developer.salesforce.com/forums/?id=906F00000008wqLIAQ

With that in mind, I might end start to use them - either way, I think it´d be nice to have in the framework :+1:

**Comment by jongpie** [comment]
Just adding another link with some limits info for future reference - https://developer.salesforce.com/docs/atlas.en-us.salesforce_app_limits_cheatsheet.meta/salesforce_app_limits_cheatsheet/salesforce_app_limits_platform_soslsoql.htm
