### ISSUE TITLE
Add CRUD DML methods to repositories

### ISSUE THREAD

**Issue by jongpie** [jongpie/NebulaFramework#18]

**Comment by jamessimone** [comment]
gotta think about the best naming convention for the database calls ...

**Comment by jongpie** [comment]
Agreed! Because 'insert', 'update', 'upsert' and 'delete' are sometimes reserved, right now, I'm thinking...
* save() - upsert
* purge() - delete (with optional boolean parameter for hard delete)
* restore() - undelete

**Comment by jongpie** [comment]
@jamessimone as discussed, your method names were mo' betta than mine, so I've used your format of doInsert, doUpdate, etc.

**Comment by jamessimone** [comment]
Let's close this!  It's done!

**Comment by jongpie** [comment]
Aww yiss! It'll get closed auto-magically as soon as I merge my PR!
