### ISSUE TITLE
Eliminate SOQLUtils.cls

### ISSUE THREAD

**Issue by jongpie** [jongpie/NebulaFramework#4]
_From @jongpie on March 2, 2017 11:1_

I really hate random utility classes that are only used by one other class.

_Copied from original issue: jongpie/ApexQueryGenerator#21_

**Comment by jamessimone** [comment]
I actually like SOQLUtils.  SRP and all that.  I would also expect that as the framework is adopted it would be used in more classes.

**Comment by jongpie** [comment]
Yeah, I was planning to scrap it because I was aiming to make a managed package and there are some strange limits with managed packages where once you add a class to a package, it can be a pain to remove later, so I was hoping to minimise the number of classes. But I agree with it being a better fit with SRP... Let me tinker with it a bit more, maybe I may hold onto the class.
