### ISSUE TITLE
Add custom class to improve schedulable classes

### ISSUE THREAD

**Issue by jongpie** [jongpie/NebulaFramework#42]

**Comment by jamessimone** [comment]
Improve in what way?

**Comment by jongpie** [comment]
Yo - the main thing I had in mind when I wrote this was having some extra methods in an abstract class to add things like scheduleDailyJob() & scheduleHourlyJob() methods, maybe a method to auto-generate a name for scheduled jobs, etc.

**Comment by jamessimone** [comment]
Ah the reason I asked is because I have a very pared down Scheduler class that I can send along - it doesn't do have the auto-naming capability you mentioned, but otherwise fits the bill

**Comment by jongpie** [comment]
Yeah, man - feel free to add it to the repo if you've got something! I'm not worried about the auto-naming bit right now, I think that could be added later if needed
