### ISSUE TITLE
Add support for passing a list of Schema.SObjectField instead of a field set

### ISSUE THREAD

**Issue by jongpie** [jongpie/NebulaFramework#5]
_From @jongpie on March 2, 2017 6:26_

Some standard objects don't allow field sets to be created - to give more flexibility, there should be a second constructor for SObjectRepository that accepts List<Schema.SObjectField> as an alternative to passing a field set.

_Copied from original issue: jongpie/ApexQueryGenerator#20_

**Comment by jongpie** [comment]
_From @jamessimone on March 3, 2017 3:50_

(clap)

**Comment by jamessimone** [comment]
also done!
