### ISSUE TITLE
QueryFilter.getValue will fail when passed a set or map

### ISSUE THREAD

**Issue by jamessimone** [jongpie/NebulaFramework#54]
Hey man, just wanted to clue you in to a runtime compilation issue between the object / List<Object> in apex.  I really liked moving the call to getValue from QueryBuilder to QueryFilter, but you will get an issue calling QueryArgumentFormatter if there are multiple values in your QueryFilter (IE, a list of Ids): 
"System.QueryException: expecting a colon, found '('"

We used to have some conditional logic in QueryBuilder to handle this based on the size of the values in the QueryFilter, but after taking another pass through your dev branch I saw that it can also be addressed by the following:

    public String getValue() {
        return this.field + ' ' + this.operator.getValue() + ' ' + this.getFormattedValues();
    }

    private String getFormattedValues() {
        return this.values.size() == 1 ? QueryArgumentFormatter.(this.values[0]).getValue() : QueryArgumentFormatter.(this.values).getValue();
    }

**Comment by jongpie** [comment]
Yo - sorry for the late reply, I  just now saw that you added this issue. Any chance you have some sample code that shows the issue in action? I think I understand but just want to be sure I'm clear on it.

**Comment by jongpie** [comment]
Hey man - either I've already fixed the bug at some point or I'm doing something wrong with trying to reproduce it, but everything seems to be working with lists - halp?

I'm using this repo...
```
public with sharing class LeadRepository extends SObjectRepository {
    public LeadRepository() {
        super(Schema.Lead.SObjectType);
    }
}
```
Then I run this script to try to reproduce the error 
```
//Yes, I know this line is ridiculous and awful to read, don't judge me. It gets some IDs to use as the query filter
List<Id> ids = new List<Id>(new Map<Id, Lead>([SELECT Id FROM Lead]).keySet()); 

//Pass the IDs to repo --> repo calls query builder --> queryfilter --> queryargumentformatter parses the list of IDs, so this seems like a valid way to try to reproduce the issue I think?
List<lead> leads = new LeadRepository().getById(ids); 

//Save the logs so I can get the generated query
Logger.saveLogs();
```

And it successfully generates & runs this query (instead of failing like I thought it would)
```
SELECT address, annualrevenue, city, cleanstatus, company, companydunsnumber, convertedaccountid, convertedcontactid, converteddate, convertedopportunityid, country, createdbyid, createddate, dandbcompanyid, description, donotcall, email, emailbounceddate, emailbouncedreason, fax, firstname, geocodeaccuracy, hasoptedoutofemail, hasoptedoutoffax, id, industry, isconverted, isdeleted, isunreadbyowner, jigsaw, jigsawcontactid, lastactivitydate, lastmodifiedbyid, lastmodifieddate, lastname, lastreferenceddate, lasttransferdate, lastvieweddate, latitude, leadsource, longitude, masterrecordid, mobilephone, name, nebula__currentgenerators__c, nebula__numberoflocations__c, nebula__primary__c, nebula__productinterest__c, nebula__siccode__c, nebula__uuid__c, numberofemployees, ownerid, phone, photourl, postalcode, rating, recordtypeid, salutation, state, status, street, systemmodstamp, title, website
FROM Lead
WHERE Id IN ('00Q0Y000005aaUSUAY','00Q0Y000005aaUXUAY','00Q0Y000002lkTmUAI','00Q0Y000002lkU1UAI','00Q0Y000002lkxTUAQ','00Q0Y000002ljfrUAA')
```

**Comment by jongpie** [comment]
Ok, I just ran this script too, and it's still working with a list of IDs 
```
List<Id> ids = new List<Id>(new Map<Id, Lead>([SELECT Id FROM Lead]).keySet());
String value = new QueryArgumentFormatter(ids).getValue();
System.debug(value);
```

 the debug statement shows this, which seems to be formatted correctly
```
01:34:14:039` USER_DEBUG [3]|DEBUG|('00Q0Y000005aaUSUAY','00Q0Y000005aaUXUAY','00Q0Y000002lkTmUAI','00Q0Y000002lkU1UAI','00Q0Y000002lkxTUAQ','00Q0Y000002ljfrUAA','00Q0Y000002lkxxUAA','00Q0Y000002lp89UAA','00Q0Y000002lkTrUAI','00Q0Y000002lkV4UAI','00Q0Y000002lkylUAA','00Q0Y000002lkybUAA','00Q0Y000002lkVOUAY','00Q0Y000002lZQNUA2','00Q0Y000002lkwpUAA','00Q0Y000002leyDUAQ','00Q0Y000002leyEUAQ','00Q0Y000002leyFUAQ','00Q0Y000002leyGUAQ','00Q0Y000002leyHUAQ','00Q0Y000002lkz5UAA','00Q0Y000002lkygUAA','00Q0Y000002lkV9UAI','00Q0Y000002lt3JUAQ','00Q0Y000002lkxEUAQ','00Q0Y000002lkyvUAA','00Q0Y000002ljg1UAA','00Q0Y000002ljgBUAQ','00Q0Y000003RwjhUAC','00Q0Y000003RwjiUAC','00Q0Y000003RwjjUAC','00Q0Y000003RwjkUAC','00Q0Y000003RwjlUAC','00Q0Y000003RwjmUAC','00Q0Y000003RwjnUAC','00Q0Y000003RwjoUAC','00Q0Y000003RwjpUAC','00Q0Y000003RwjqUAC','00Q0Y000003RwjrUAC','00Q0Y000003RwjsUAC','00Q0Y000003RwjtUAC','00Q0Y000003RwjuUAC','00Q0Y000003RwjvUAC','00Q0Y000003RwjwUAC','00Q0Y000003RwjxUAC','00Q0Y000003RwjyUAC','00Q0Y000003RwjzUAC','00Q0Y000003Rwk0UAC','00Q0Y000003Rwk1UAC','00Q0Y000003Rwk2UAC')
```

**Bonus** :ping_pong: and :neckbeard: emojis because I just learned that github has them.

**Comment by jamessimone** [comment]
@jongpie hey man, I am realizing that the issue was due to us having static accessors for QueryFilter which take care of adding the QueryOperator (so we do some additional juggling to prevent QueryArgumentFormatter from adding parentheses if the list only contains a single Id and the operator is "=" instead of "in").  

However - try passing a set of Id's / Strings instead.  Different issue, same end result.  We have many instances where we are passing sets of either email addresses or Ids around so as to ensure uniqueness.

**Comment by jongpie** [comment]
@jamessimone it turns out that the `instanceof` keyword in Apex doesn't work properly with sets or maps... so that's pretty neat. I've got a workaround almost done for this ticket though - I'll include it in the v1.0 release as well.

**Comment by jamessimone** [comment]
@jongpie haha yes.  I could have sworn I told you about this bug with the compiler before!  Curiously (I don't know if you debugged this), at least for Sets, the compiler knows that they are an instanceof Iterable, but nothing more than that.

**Comment by jongpie** [comment]
This is dumb, Salesforce should fix it! The CollectionUtils class that I've added to #63 works around it (in a very ugly but effective way), but Salesforce should stop being so silly. 

Anywho, I need to do a bit more clean up and add some more unit tests, then this should be ready for review. I'll add you as reviewer once I finish up (might be tomorrow though).

**Comment by jongpie** [comment]
> hey man, I am realizing that the issue was due to us having static accessors for QueryFilter which take care of adding the QueryOperator (so we do some additional juggling to prevent QueryArgumentFormatter from adding parentheses if the list only contains a single Id and the operator is "=" instead of "in").

@jamessimone I think I get the idea of what you're saying here, but why are you switching it from 'in' to '=' when it's a list with 1 value? It seems like an unnecessary step - couldn't you just leave it as 'IN'? 

For list variables, using 'IN' and '=' give the same results ([source](https://salesforce.stackexchange.com/questions/165416/is-in-operator-equivalent-to-equal-operator-in-soql-when-binding-a-list-variable?noredirect=1&lq=1)) but I definitely might be misunderstanding what you've implemented.
